# Dotbro configuration file.
#
# Some points:
# - Almost all options have default value.
# - You can use $ENV_VARIABLE in paths.

[directories]

# Directory of your dotfiles repository.
# Default: directory of this config.
dotfiles = "$DOTFILES"

# Destination directory - your dotfiles will be linked there.
# Default: $HOME
destination = "$HOME"

# Backup directory - your original files will be backuped there.
# Default: $HOME/.dotfiles~
backup = "$HOME/.etc.bkp~"

[mapping]
"alacritty" = "$XDG_CONFIG_HOME/alacritty"
"awesome" = "$XDG_CONFIG_HOME/awesome"
"bat" = "$XDG_CONFIG_HOME/bat"
"beets" =  "$XDG_CONFIG_HOME/beets"
"BetterDiscord" = "$XDG_CONFIG_HOME/BetterDiscord"
"bin" = "bin"
"cava" = "$XDG_CONFIG_HOME/cava"
"compton/compton.conf" = "$XDG_CONFIG_HOME/compton.conf"
"doom" = "$XDG_CONFIG_HOME/doom"
"dotbro" = "$XDG_CONFIG_HOME/dotbro"
"dunst" = "$XDG_CONFIG_HOME/dunst"
"emacs.d" = ".emacs.d"
"fish" = "$XDG_CONFIG_HOME/fish"
"fontconfig" = "$XDG_CONFIG_HOME/fontconfig"
"fonts" = "$XDG_DATA_HOME/fonts"
"git" = "$XDG_CONFIG_HOME/git"
"gtk/gtkrc" = "$XDG_CONFIG_HOME/gtkrc"
"htop" = "$XDG_CONFIG_HOME/htop"
"mpd" = "$XDG_CONFIG_HOME/mpd"
"mpv" = "$XDG_CONFIG_HOME/mpv"
"ncmpcpp" = "$XDG_CONFIG_HOME/ncmpcpp"
"nvim" = "$XDG_CONFIG_HOME/nvim"
"profile" = ".profile"
"ranger" = "$XDG_CONFIG_HOME/ranger"
"termite" = "$XDG_CONFIG_HOME/termite"
"themes" = "$XDG_DATA_HOME/themes"
"tmux" = "$XDG_CONFIG_HOME/tmux"
"weechat" = ".weechat"
"xorg" = "$XDG_CONFIG_HOME/xorg"
"yay" = "$XDG_CONFIG_HOME/yay"
