# Dotbro configuration file.
#
# Some points:
# - Almost all options have default value.
# - You can use $ENV_VARIABLE in paths.

[directories]

# Directory of your dotfiles repository.
# Default: directory of this config.
dotfiles = "$DOTFILES"

# Destination directory - your dotfiles will be linked there.
# Default: $HOME
destination = "$HOME"

# Backup directory - your original files will be backuped there.
# Default: $HOME/.dotfiles~
backup = "$HOME/.etc.bkp~"

[mapping]
"alacritty" = ".config/alacritty"
"awesome" = ".config/awesome"
"bat" = ".config/bat"
"beets" =  ".config/beets"
"BetterDiscord" = ".config/BetterDiscord"
"bin" = "bin"
"cava" = ".config/cava"
"compton/compton.conf" = ".config/compton.conf"
"dotbro" = ".config/dotbro"
"dunst" = ".config/dunst"
"fish" = ".config/fish"
"fontconfig" = ".config/fontconfig"
"fonts" = "usr/share/fonts"
"git" = ".config/git"
"gtk/gtkrc" = ".config/gtkrc"
"htop" = ".config/htop"
"mpd" = ".config/mpd"
"mpv" = ".config/mpv"
"ncmpcpp" = ".config/ncmpcpp"
"profile" = ".profile"
"ranger" = ".config/ranger"
"termite" = ".config/termite"
"themes" = ".local/share/themes"
"tmux" = ".config/tmux"
"weechat" = ".weechat"
"xorg" = ".config/xorg"
"yay" = ".config/yay"
