#!/bin/sh -x
. /home/brett/.profile

test -r "$XDG_CONFIG_HOME"/xorg/xres && xrdb -load "$XDG_CONFIG_HOME"/xorg/xres

xrandr --dpi 110 &
xsetroot -cursor_name left_ptr &

# pgrep librespot  || lnch librespot -n "uwu" -b 320
# pgrep unclutter  || lnch unclutter

export GDK_BACKEND=x11
exec gnome-session
